/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateDreowacisRouteImport } from './routes/create.dreowacis'
import { Route as CreateSystemRouteImport } from './routes/create.$system'
import { Route as CreateDreowacisIndexRouteImport } from './routes/create.dreowacis.index'
import { Route as CreateSystemIndexRouteImport } from './routes/create.$system.index'
import { Route as CreateDreowacisReinoRouteImport } from './routes/create.dreowacis.reino'
import { Route as CreateDreowacisRacaRouteImport } from './routes/create.dreowacis.raca'
import { Route as CreateDreowacisPericiasRouteImport } from './routes/create.dreowacis.pericias'
import { Route as CreateDreowacisFichaRouteImport } from './routes/create.dreowacis.ficha'
import { Route as CreateDreowacisDevocaoRouteImport } from './routes/create.dreowacis.devocao'
import { Route as CreateDreowacisAtributosRouteImport } from './routes/create.dreowacis.atributos'
import { Route as CreateSystemSheetRouteImport } from './routes/create.$system.sheet'
import { Route as CreateSystemRaceRouteImport } from './routes/create.$system.race'
import { Route as CreateSystemDetailsRouteImport } from './routes/create.$system.details'
import { Route as CreateSystemClassRouteImport } from './routes/create.$system.class'
import { Route as CreateSystemAbilitiesRouteImport } from './routes/create.$system.abilities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDreowacisRoute = CreateDreowacisRouteImport.update({
  id: '/create/dreowacis',
  path: '/create/dreowacis',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSystemRoute = CreateSystemRouteImport.update({
  id: '/create/$system',
  path: '/create/$system',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDreowacisIndexRoute = CreateDreowacisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateDreowacisRoute,
} as any)
const CreateSystemIndexRoute = CreateSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateSystemRoute,
} as any)
const CreateDreowacisReinoRoute = CreateDreowacisReinoRouteImport.update({
  id: '/reino',
  path: '/reino',
  getParentRoute: () => CreateDreowacisRoute,
} as any)
const CreateDreowacisRacaRoute = CreateDreowacisRacaRouteImport.update({
  id: '/raca',
  path: '/raca',
  getParentRoute: () => CreateDreowacisRoute,
} as any)
const CreateDreowacisPericiasRoute = CreateDreowacisPericiasRouteImport.update({
  id: '/pericias',
  path: '/pericias',
  getParentRoute: () => CreateDreowacisRoute,
} as any)
const CreateDreowacisFichaRoute = CreateDreowacisFichaRouteImport.update({
  id: '/ficha',
  path: '/ficha',
  getParentRoute: () => CreateDreowacisRoute,
} as any)
const CreateDreowacisDevocaoRoute = CreateDreowacisDevocaoRouteImport.update({
  id: '/devocao',
  path: '/devocao',
  getParentRoute: () => CreateDreowacisRoute,
} as any)
const CreateDreowacisAtributosRoute =
  CreateDreowacisAtributosRouteImport.update({
    id: '/atributos',
    path: '/atributos',
    getParentRoute: () => CreateDreowacisRoute,
  } as any)
const CreateSystemSheetRoute = CreateSystemSheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => CreateSystemRoute,
} as any)
const CreateSystemRaceRoute = CreateSystemRaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => CreateSystemRoute,
} as any)
const CreateSystemDetailsRoute = CreateSystemDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => CreateSystemRoute,
} as any)
const CreateSystemClassRoute = CreateSystemClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => CreateSystemRoute,
} as any)
const CreateSystemAbilitiesRoute = CreateSystemAbilitiesRouteImport.update({
  id: '/abilities',
  path: '/abilities',
  getParentRoute: () => CreateSystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create/$system': typeof CreateSystemRouteWithChildren
  '/create/dreowacis': typeof CreateDreowacisRouteWithChildren
  '/create/$system/abilities': typeof CreateSystemAbilitiesRoute
  '/create/$system/class': typeof CreateSystemClassRoute
  '/create/$system/details': typeof CreateSystemDetailsRoute
  '/create/$system/race': typeof CreateSystemRaceRoute
  '/create/$system/sheet': typeof CreateSystemSheetRoute
  '/create/dreowacis/atributos': typeof CreateDreowacisAtributosRoute
  '/create/dreowacis/devocao': typeof CreateDreowacisDevocaoRoute
  '/create/dreowacis/ficha': typeof CreateDreowacisFichaRoute
  '/create/dreowacis/pericias': typeof CreateDreowacisPericiasRoute
  '/create/dreowacis/raca': typeof CreateDreowacisRacaRoute
  '/create/dreowacis/reino': typeof CreateDreowacisReinoRoute
  '/create/$system/': typeof CreateSystemIndexRoute
  '/create/dreowacis/': typeof CreateDreowacisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create/$system/abilities': typeof CreateSystemAbilitiesRoute
  '/create/$system/class': typeof CreateSystemClassRoute
  '/create/$system/details': typeof CreateSystemDetailsRoute
  '/create/$system/race': typeof CreateSystemRaceRoute
  '/create/$system/sheet': typeof CreateSystemSheetRoute
  '/create/dreowacis/atributos': typeof CreateDreowacisAtributosRoute
  '/create/dreowacis/devocao': typeof CreateDreowacisDevocaoRoute
  '/create/dreowacis/ficha': typeof CreateDreowacisFichaRoute
  '/create/dreowacis/pericias': typeof CreateDreowacisPericiasRoute
  '/create/dreowacis/raca': typeof CreateDreowacisRacaRoute
  '/create/dreowacis/reino': typeof CreateDreowacisReinoRoute
  '/create/$system': typeof CreateSystemIndexRoute
  '/create/dreowacis': typeof CreateDreowacisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create/$system': typeof CreateSystemRouteWithChildren
  '/create/dreowacis': typeof CreateDreowacisRouteWithChildren
  '/create/$system/abilities': typeof CreateSystemAbilitiesRoute
  '/create/$system/class': typeof CreateSystemClassRoute
  '/create/$system/details': typeof CreateSystemDetailsRoute
  '/create/$system/race': typeof CreateSystemRaceRoute
  '/create/$system/sheet': typeof CreateSystemSheetRoute
  '/create/dreowacis/atributos': typeof CreateDreowacisAtributosRoute
  '/create/dreowacis/devocao': typeof CreateDreowacisDevocaoRoute
  '/create/dreowacis/ficha': typeof CreateDreowacisFichaRoute
  '/create/dreowacis/pericias': typeof CreateDreowacisPericiasRoute
  '/create/dreowacis/raca': typeof CreateDreowacisRacaRoute
  '/create/dreowacis/reino': typeof CreateDreowacisReinoRoute
  '/create/$system/': typeof CreateSystemIndexRoute
  '/create/dreowacis/': typeof CreateDreowacisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create/$system'
    | '/create/dreowacis'
    | '/create/$system/abilities'
    | '/create/$system/class'
    | '/create/$system/details'
    | '/create/$system/race'
    | '/create/$system/sheet'
    | '/create/dreowacis/atributos'
    | '/create/dreowacis/devocao'
    | '/create/dreowacis/ficha'
    | '/create/dreowacis/pericias'
    | '/create/dreowacis/raca'
    | '/create/dreowacis/reino'
    | '/create/$system/'
    | '/create/dreowacis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create/$system/abilities'
    | '/create/$system/class'
    | '/create/$system/details'
    | '/create/$system/race'
    | '/create/$system/sheet'
    | '/create/dreowacis/atributos'
    | '/create/dreowacis/devocao'
    | '/create/dreowacis/ficha'
    | '/create/dreowacis/pericias'
    | '/create/dreowacis/raca'
    | '/create/dreowacis/reino'
    | '/create/$system'
    | '/create/dreowacis'
  id:
    | '__root__'
    | '/'
    | '/create/$system'
    | '/create/dreowacis'
    | '/create/$system/abilities'
    | '/create/$system/class'
    | '/create/$system/details'
    | '/create/$system/race'
    | '/create/$system/sheet'
    | '/create/dreowacis/atributos'
    | '/create/dreowacis/devocao'
    | '/create/dreowacis/ficha'
    | '/create/dreowacis/pericias'
    | '/create/dreowacis/raca'
    | '/create/dreowacis/reino'
    | '/create/$system/'
    | '/create/dreowacis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateSystemRoute: typeof CreateSystemRouteWithChildren
  CreateDreowacisRoute: typeof CreateDreowacisRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/dreowacis': {
      id: '/create/dreowacis'
      path: '/create/dreowacis'
      fullPath: '/create/dreowacis'
      preLoaderRoute: typeof CreateDreowacisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$system': {
      id: '/create/$system'
      path: '/create/$system'
      fullPath: '/create/$system'
      preLoaderRoute: typeof CreateSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/dreowacis/': {
      id: '/create/dreowacis/'
      path: '/'
      fullPath: '/create/dreowacis/'
      preLoaderRoute: typeof CreateDreowacisIndexRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/$system/': {
      id: '/create/$system/'
      path: '/'
      fullPath: '/create/$system/'
      preLoaderRoute: typeof CreateSystemIndexRouteImport
      parentRoute: typeof CreateSystemRoute
    }
    '/create/dreowacis/reino': {
      id: '/create/dreowacis/reino'
      path: '/reino'
      fullPath: '/create/dreowacis/reino'
      preLoaderRoute: typeof CreateDreowacisReinoRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/dreowacis/raca': {
      id: '/create/dreowacis/raca'
      path: '/raca'
      fullPath: '/create/dreowacis/raca'
      preLoaderRoute: typeof CreateDreowacisRacaRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/dreowacis/pericias': {
      id: '/create/dreowacis/pericias'
      path: '/pericias'
      fullPath: '/create/dreowacis/pericias'
      preLoaderRoute: typeof CreateDreowacisPericiasRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/dreowacis/ficha': {
      id: '/create/dreowacis/ficha'
      path: '/ficha'
      fullPath: '/create/dreowacis/ficha'
      preLoaderRoute: typeof CreateDreowacisFichaRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/dreowacis/devocao': {
      id: '/create/dreowacis/devocao'
      path: '/devocao'
      fullPath: '/create/dreowacis/devocao'
      preLoaderRoute: typeof CreateDreowacisDevocaoRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/dreowacis/atributos': {
      id: '/create/dreowacis/atributos'
      path: '/atributos'
      fullPath: '/create/dreowacis/atributos'
      preLoaderRoute: typeof CreateDreowacisAtributosRouteImport
      parentRoute: typeof CreateDreowacisRoute
    }
    '/create/$system/sheet': {
      id: '/create/$system/sheet'
      path: '/sheet'
      fullPath: '/create/$system/sheet'
      preLoaderRoute: typeof CreateSystemSheetRouteImport
      parentRoute: typeof CreateSystemRoute
    }
    '/create/$system/race': {
      id: '/create/$system/race'
      path: '/race'
      fullPath: '/create/$system/race'
      preLoaderRoute: typeof CreateSystemRaceRouteImport
      parentRoute: typeof CreateSystemRoute
    }
    '/create/$system/details': {
      id: '/create/$system/details'
      path: '/details'
      fullPath: '/create/$system/details'
      preLoaderRoute: typeof CreateSystemDetailsRouteImport
      parentRoute: typeof CreateSystemRoute
    }
    '/create/$system/class': {
      id: '/create/$system/class'
      path: '/class'
      fullPath: '/create/$system/class'
      preLoaderRoute: typeof CreateSystemClassRouteImport
      parentRoute: typeof CreateSystemRoute
    }
    '/create/$system/abilities': {
      id: '/create/$system/abilities'
      path: '/abilities'
      fullPath: '/create/$system/abilities'
      preLoaderRoute: typeof CreateSystemAbilitiesRouteImport
      parentRoute: typeof CreateSystemRoute
    }
  }
}

interface CreateSystemRouteChildren {
  CreateSystemAbilitiesRoute: typeof CreateSystemAbilitiesRoute
  CreateSystemClassRoute: typeof CreateSystemClassRoute
  CreateSystemDetailsRoute: typeof CreateSystemDetailsRoute
  CreateSystemRaceRoute: typeof CreateSystemRaceRoute
  CreateSystemSheetRoute: typeof CreateSystemSheetRoute
  CreateSystemIndexRoute: typeof CreateSystemIndexRoute
}

const CreateSystemRouteChildren: CreateSystemRouteChildren = {
  CreateSystemAbilitiesRoute: CreateSystemAbilitiesRoute,
  CreateSystemClassRoute: CreateSystemClassRoute,
  CreateSystemDetailsRoute: CreateSystemDetailsRoute,
  CreateSystemRaceRoute: CreateSystemRaceRoute,
  CreateSystemSheetRoute: CreateSystemSheetRoute,
  CreateSystemIndexRoute: CreateSystemIndexRoute,
}

const CreateSystemRouteWithChildren = CreateSystemRoute._addFileChildren(
  CreateSystemRouteChildren,
)

interface CreateDreowacisRouteChildren {
  CreateDreowacisAtributosRoute: typeof CreateDreowacisAtributosRoute
  CreateDreowacisDevocaoRoute: typeof CreateDreowacisDevocaoRoute
  CreateDreowacisFichaRoute: typeof CreateDreowacisFichaRoute
  CreateDreowacisPericiasRoute: typeof CreateDreowacisPericiasRoute
  CreateDreowacisRacaRoute: typeof CreateDreowacisRacaRoute
  CreateDreowacisReinoRoute: typeof CreateDreowacisReinoRoute
  CreateDreowacisIndexRoute: typeof CreateDreowacisIndexRoute
}

const CreateDreowacisRouteChildren: CreateDreowacisRouteChildren = {
  CreateDreowacisAtributosRoute: CreateDreowacisAtributosRoute,
  CreateDreowacisDevocaoRoute: CreateDreowacisDevocaoRoute,
  CreateDreowacisFichaRoute: CreateDreowacisFichaRoute,
  CreateDreowacisPericiasRoute: CreateDreowacisPericiasRoute,
  CreateDreowacisRacaRoute: CreateDreowacisRacaRoute,
  CreateDreowacisReinoRoute: CreateDreowacisReinoRoute,
  CreateDreowacisIndexRoute: CreateDreowacisIndexRoute,
}

const CreateDreowacisRouteWithChildren = CreateDreowacisRoute._addFileChildren(
  CreateDreowacisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateSystemRoute: CreateSystemRouteWithChildren,
  CreateDreowacisRoute: CreateDreowacisRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
